[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "arxiv>=2.3.1",
    "ddgs>=9.9.3",
    "openai>=2.9.0",
    "requests>=2.32.5",
    "streamlit>=1.52.1",
    "wikipedia-api>=0.8.1",
]
